#MySQL 의존성을 주석 처리한 경우, 애플리케이션에 사용할 다른 데이터베이스를 설정하거나 내장 데이터 소스를 사용하지 않도록 명시적으로 설정할 수 있습니다. 이를 위해 application.properties 또는 application.yml 파일에서 다음과 같이 내장 데이터 소스를 비활성화할 수 있습니다:
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# 이게 기본경로 defualt값이다
#server:
#  port:8080
#  servlet:
#    context-path: /


#blog 프로젝트 읽기 직저에 여기를 먼저 읽는다 
server:
  port: 8000
  servlet:
    context-path: /blog #이거를 localhost8000/blog/나머지입력    이렇게 입력해야 접속이 가능하다
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring: 
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource: #데이터베이스 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # update:기존의 있는 데이터의 변경이 된다  ,none:db에 아무런 반영을 하지 않음 ,create:테이블 새로 만든다= 프로그램 실행할때마다
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #엔티티(테이블)을 만들때 변수명(필드명) 그대로 테이블을 만들어준다는거다 
      use-new-id-generator-mappings: false # jpa가 사용하는 사용하는 기본전략을 따라가지 않는다
    show-sql: true #콘솔창에 테이블 생성한거를 볼수 있다
    properties:
      hibernate.format_sql: true # 원래는 테이블 생성할때 한줄로 나오는데 이걸 활용해서 콘솔창에서 정렬해서 볼수 있다

  jackson:
    serialization:
      fail-on-empty-beans: false
      